creation_rules:
  - path_regex: ^secrets/.*\.env\.enc$
    input_type: dotenv
    output_type: dotenv
    age: >-
      age1lcgsswm7ycfpnlwyul6yh4g84l6lwhmwzehu5sxfhs06vdnjusxqma938u,
      age1tqhqpn77enh2nskt7flkzah8eanmtsg2m7ef3wvm2gkul30h7ausf2mhy2
