import React,{useState,useRef,useEffect,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Player,type PlayerRef} from '@remotion/player';
import {ShortVideo} from '../src/ShortVideo';
import {validateDiagram,diagramState} from '../src/visuals/diagram-spec';
import {assertDiagramLayout,layoutSampleTimes,resolveConnectors} from '../src/visuals/layout-guard';
import {STICKER_USAGE,STICKER_ATTACHMENTS} from '../src/visuals/notebook-catalog';
import {timedBeats} from '../src/subtitles';
import {staticFile} from 'remotion';
const base=(window as any).REVIEW_CANDIDATE;
import {clone,fresh as makeFresh,parseDraft as readDraft,type Layout,type Draft} from './model';
const fresh=()=>makeFresh(base);
const parseDraft=(raw:string)=>readDraft(raw,base);
const storageKey='notebook-review-v1:'+base.source.url;
type Box={x:number;y:number;width:number;height:number};
const defaults:Record<string,Box>={photo:{x:90,y:685,width:840,height:560},diagram:{x:60,y:500,width:900,height:630},title:{x:90,y:240,width:800,height:140},openingTitle:{x:90,y:260,width:800,height:350},caption:{x:90,y:1340,width:590,height:168},note:{x:90,y:1410,width:570,height:140}};
const names:Record<string,string>={photo:'사진 + 테이프',diagram:'도식 영역',title:'전체 주제 제목',openingTitle:'오프닝 제목',caption:'자막',note:'오프닝 메모'};
const selectors:Record<string,string>={photo:'[data-overlay-reserve="opening-photo"]',diagram:'[data-overlay-reserve="notebook"]',title:'div:has(> [data-layout-text="headline"])',openingTitle:'[data-layout-text="opening-title"]',caption:'[data-layout="caption"]',note:'[data-layout-text="opening-note"]'};
function download(name:string,data:string,type='application/json'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
class Boundary extends React.Component<{children:React.ReactNode},{error:string|null}>{state={error:null};static getDerivedStateFromError(e:Error){return {error:e.message}}render(){return this.state.error?<div className="empty">배치를 표시할 수 없습니다. 실행 취소하거나 선택한 값을 수정해 주세요.<pre>{this.state.error}</pre></div>:this.props.children}}
function App(){
 const [draft,setDraft]=useState<Draft>(()=>{try{return parseDraft(localStorage.getItem(storageKey)||'')}catch{return fresh()}});
 const [index,setIndex]=useState(0),[selected,setSelected]=useState('photo'),[editing,setEditing]=useState(true),[frame,setFrame]=useState(60),[tab,setTab]=useState('layout'),[flash,setFlash]=useState(''),[saveState,setSaveState]=useState('');
 const undo=useRef<Draft[]>([]),redo=useRef<Draft[]>([]),drag=useRef<any>(null),canvas=useRef<HTMLDivElement>(null),player=useRef<PlayerRef>(null),file=useRef<HTMLInputElement>(null);
 const scene=draft.candidate.scenes[index],opening=scene.layout==='notebook-title',common=!!scene.commonPage;
 const groups=common?[]:opening?['openingTitle','photo','note']:['title','diagram','caption'];
 const duration=Math.max(3.6,scene.narration.replace(/\s/g,'').length/7.5),frames=Math.max(66,Math.ceil((duration+.28)*30));
 const renderScene={...scene,imagePath:opening?'notebook/opening-photo.jpg':null,audioPath:null,audioDurationSeconds:duration,overlayPresenter:null};
 const renderProps={...draft.candidate,scenes:[renderScene],presenterOverlay:draft.candidate.presenterOverlay?{...draft.candidate.presenterOverlay,lipSync:'none',nod:'none'}:null};
 const getLayout=(key:string):Layout=>draft.layouts[`${index}:${key}`]||{dx:0,dy:0,scale:1};
 const groupBox=(key:string):Box=>{const b=defaults[key],l=getLayout(key);return{x:b.x+l.dx,y:b.y+l.dy,width:b.width*l.scale,height:b.height*l.scale}};
 const spec=scene.diagramSpec;
 const states=useMemo(()=>spec?resolveConnectors(diagramState(spec,frame/Math.max(1,frames-1))):[],[spec,frame,frames]);
 const node=spec?.nodes.find((n:any)=>n.id===selected),state=states.find((n:any)=>n.id===selected);
 const box=node&&state?(()=>{const b=groupBox('diagram');return{x:b.x+(state.x-state.width/2)*b.width/800,y:b.y+(state.y-state.height/2)*b.height/560,width:state.width*b.width/800,height:state.height*b.height/560}})():groups.includes(selected)?groupBox(selected):null;
 const diagnostics=useMemo(()=>{const issues:string[]=[];if(spec)try{validateDiagram(spec);for(const t of layoutSampleTimes(spec))assertDiagramLayout(resolveConnectors(diagramState(spec,t)),t,spec.notebook)}catch(e){issues.push((e as Error).message)}
 const boxes=groups.map(k=>({key:k,...groupBox(k)}));for(const b of boxes)if(b.x<0||b.y<0||b.x+b.width>1080||b.y+b.height>1920)issues.push(`${names[b.key]} 영역이 화면을 벗어납니다.`);
 const visual=boxes.find(b=>b.key==='photo'||b.key==='diagram');if(visual)for(const b of boxes.filter(b=>b!==visual))if(b.x<visual.x+visual.width&&b.x+b.width>visual.x&&b.y<visual.y+visual.height&&b.y+b.height>visual.y)issues.push(`${names[b.key]} 영역과 ${names[visual.key]} 영역이 겹칩니다.`);
 return issues;},[draft,index]);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(draft));setSaveState('이 브라우저에 저장됨')}catch{setSaveState('자동 저장 불가 · JSON을 저장해 주세요')}},[draft]);
 useEffect(()=>{const p=player.current;if(!p)return;const f=(e:any)=>setFrame(e.detail.frame);p.addEventListener('frameupdate',f);p.seekTo(60);return()=>p.removeEventListener('frameupdate',f)},[index]);
 useEffect(()=>{if(!flash)return;const id=setTimeout(()=>setFlash(''),4500);return()=>clearTimeout(id)},[flash]);
 function commit(next:Draft){undo.current.push(clone(draft));if(undo.current.length>80)undo.current.shift();redo.current=[];setDraft(next)}
 function history(back:boolean){const from=back?undo.current:redo.current,to=back?redo.current:undo.current;const d=from.pop();if(d){to.push(clone(draft));setDraft(d)}}
 function chooseScene(i:number){setIndex(i);setSelected(draft.candidate.scenes[i].layout==='notebook-title'?'photo':'diagram');setFrame(60)}
 function updateValues(values:Record<string,number>,record=true,original=draft){const next=clone(original);if(node){const n=next.candidate.scenes[index].diagramSpec.nodes.find((n:any)=>n.id===selected);for(const[k,v]of Object.entries(values)){if(!Number.isFinite(v))continue;const limit=k==='x'||k==='width'?800:560;let value=Math.max(k==='width'||k==='height'?1:0,Math.min(limit,v));const events=next.candidate.scenes[index].diagramSpec.events.filter((e:any)=>e.target===n.id&&e.property===k);const lo=k==='width'||k==='height'?1:-800,hi=k==='width'||k==='height'?limit:800;const ends=events.flatMap((e:any)=>[e.from,e.to]);if(ends.length)value=n[k]+Math.max(lo-Math.min(...ends),Math.min(hi-Math.max(...ends),value-n[k]));const delta=value-n[k];n[k]=value;for(const e of next.candidate.scenes[index].diagramSpec.events)if(e.target===n.id&&e.property===k){e.from+=delta;e.to+=delta}}}else if(groups.includes(selected)){const l=next.layouts[`${index}:${selected}`]||{dx:0,dy:0,scale:1};const b=defaults[selected];if(values.x!==undefined)l.dx=values.x-b.x;if(values.y!==undefined)l.dy=values.y-b.y;if(values.width!==undefined)l.scale=Math.max(.25,Math.min(2,values.width/b.width));if(values.height!==undefined)l.scale=Math.max(.25,Math.min(2,values.height/b.height));next.layouts[`${index}:${selected}`]=l;}record?commit(next):setDraft(next)}
 function start(e:React.PointerEvent,key:string,resize=false){e.preventDefault();e.stopPropagation();player.current?.pause();setSelected(key);const target=e.currentTarget as HTMLElement;target.setPointerCapture(e.pointerId);undo.current.push(clone(draft));redo.current=[];drag.current={x:e.clientX,y:e.clientY,key,resize,original:clone(draft),scale:1080/canvas.current!.getBoundingClientRect().width};}
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const n=d.original.candidate.scenes[index].diagramSpec?.nodes.find((n:any)=>n.id===d.key);const dx=(e.clientX-d.x)*d.scale,dy=(e.clientY-d.y)*d.scale;if(n){const g=groupBox('diagram');updateValues(d.resize?{width:n.width+dx*800/g.width,height:n.height+dy*560/g.height}:{x:n.x+dx*800/g.width,y:n.y+dy*560/g.height},false,d.original)}else{const b=defaults[d.key],l=d.original.layouts[`${index}:${d.key}`]||{dx:0,dy:0,scale:1};updateValues(d.resize?{width:b.width*l.scale+dx}:{x:b.x+l.dx+dx,y:b.y+l.dy+dy},false,d.original)}}
 function addSticker(asset:string){if(!spec)return;if(spec.nodes.length>=40){setFlash('도식 객체는 최대 40개까지 추가할 수 있습니다.');return;}const next=clone(draft);let id=`note-${asset}-1`,n=1;while(spec.nodes.some((x:any)=>x.id===id))id=`note-${asset}-${++n}`;next.candidate.scenes[index].diagramSpec.nodes.push({id,role:'sticker',stickerAsset:asset,shape:'rect',label:['paper','blue'].includes(asset)?'메모':'',x:400,y:450,width:['paper','blue'].includes(asset)?160:72,height:['paper','blue'].includes(asset)?85:64,fill:'none'});commit(next);setSelected(id)}
 function attachment(field:string,value:string){const next=clone(draft),n=next.candidate.scenes[index].diagramSpec.nodes.find((x:any)=>x.id===selected);if(!value)n.stickerAttachment=null;else{const presets=Object.entries(STICKER_ATTACHMENTS).filter(([,v])=>v.assets.includes(n.stickerAsset));n.stickerAttachment={target:n.stickerAttachment?.target||spec.nodes.find((x:any)=>x.role!=='sticker'&&['rect','circle','blob'].includes(x.shape))?.id,preset:n.stickerAttachment?.preset||presets[0]?.[0],[field]:value};if(!n.stickerAttachment.target||!n.stickerAttachment.preset){setFlash('부착 대상 또는 지원되는 프리셋이 없습니다.');return}}commit(next)}
 const openingLayout=getLayout('openingTitle');
 const css=groups.map(k=>{const l=getLayout(k);return `.review-composition ${selectors[k]}{translate:${l.dx}px ${l.dy}px;scale:${l.scale};transform-origin:top left;}`}).join('\n')+(opening?`.review-composition [data-layout-text="opening-title"] + svg{translate:${openingLayout.dx}px ${openingLayout.dy+337*(openingLayout.scale-1)}px;scale:${openingLayout.scale};transform-origin:top left;}`:'');
 const beats=timedBeats(renderScene);const beat=beats.filter(b=>b.startSeconds<=frame/30).at(-1);
 const nodeKeys=spec?.nodes.filter((n:any)=>!n.connector).map((n:any)=>n.id)||[];
 return <><style>{`@font-face{font-family:Pretendard;src:url('${staticFile('fonts/Pretendard-Regular.woff')}');font-weight:400}@font-face{font-family:Pretendard;src:url('${staticFile('fonts/Pretendard-Bold.woff')}');font-weight:700 900}${css}`}</style>
 <header><div><h1>오답노트 <span style={{fontWeight:400,color:'#7b8797'}}> / 배치 검수</span></h1><small>프론트엔드와 백엔드 개발자 협업하기 · {saveState}</small></div><div className="toolbar"><button onClick={()=>history(true)} disabled={!undo.current.length}>실행 취소</button><button onClick={()=>history(false)} disabled={!redo.current.length}>다시 실행</button><button onClick={()=>file.current?.click()}>불러오기</button><button className="active" onClick={()=>download('notebook-review.json',JSON.stringify(draft,null,2))}>검수 JSON 저장</button><input ref={file} type="file" accept="application/json,.json" hidden onChange={async e=>{const f=e.target.files?.[0];if(f)try{commit(parseDraft(await f.text()));setFlash('배치와 메모를 불러왔습니다.')}catch(err){setFlash((err as Error).message)}e.target.value=''}}/></div></header>
 <main className="app"><aside className="scenes"><div className="eyebrow">STORYBOARD / 10 SCENES</div>{draft.candidate.scenes.map((s:any,i:number)=><button key={i} className={'scene '+(i===index?'active':'')} onClick={()=>chooseScene(i)}><b>{String(i+1).padStart(2,'0')} · {i===0?'오프닝':s.commonPage?'마무리':'경험 기록'}</b><span>{s.narration.slice(0,47)}{s.narration.length>47?'…':''}</span></button>)}</aside>
 <section className="stage"><div className="stagebar"><div><b>장면 {String(index+1).padStart(2,'0')}</b> <small>1080 × 1920</small></div><div className="toolbar"><button className={editing?'active':''} onClick={()=>{setEditing(!editing);player.current?.pause()}}>{editing?'배치 편집 중':'배치 편집'}</button><button onClick={()=>{setEditing(false);player.current?.toggle()}}>재생 / 정지</button></div></div>
 <div className="canvas" ref={canvas}><div className="review-composition"><Boundary key={index}><Player ref={player} component={ShortVideo} inputProps={renderProps} compositionWidth={1080} compositionHeight={1920} durationInFrames={frames} fps={30} initialFrame={60} style={{width:'100%',height:'100%'}} controls={false} acknowledgeRemotionLicense/></Boundary></div>
 {editing&&<div className="hitarea">{groups.map(k=>{const b=groupBox(k);return <div key={k} className={'handle '+(selected===k?'selected':'')} data-name={names[k]} style={{left:`${b.x/10.8}%`,top:`${b.y/19.2}%`,width:`${b.width/10.8}%`,height:`${b.height/19.2}%`}} onPointerDown={e=>start(e,k)} onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>{selected===k&&<div className="resize" onPointerDown={e=>start(e,k,true)}/>}</div>})}{states.filter((n:any)=>!n.connector&&n.opacity>0).map((n:any)=>{const g=groupBox('diagram');return <div key={n.id} className={'handle '+(selected===n.id?'selected':'')} data-name={n.id} style={{left:`${(g.x+(n.x-n.width/2)*g.width/800)/10.8}%`,top:`${(g.y+(n.y-n.height/2)*g.height/560)/19.2}%`,width:`${n.width*g.width/800/10.8}%`,height:`${n.height*g.height/560/19.2}%`,transform:`rotate(${n.rotation}deg) scale(${n.scale})`}} onPointerDown={e=>start(e,n.id)} onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>{selected===n.id&&<div className="resize" onPointerDown={e=>start(e,n.id,true)}/>}</div>})}</div>}</div>
 <div className="timeline"><span className="readout">{(frame/30).toFixed(1)}s</span><input aria-label="장면 재생 위치" type="range" min="0" max={frames-1} value={frame} onChange={e=>{setFrame(+e.target.value);player.current?.seekTo(+e.target.value)}}/><span className="readout">{(frames/30).toFixed(1)}s</span></div>
 <div className="caption"><p>{beat?.text||scene.narration}</p><small>무음 검수 · 재생 길이는 추정값입니다. 최종 TTS 타이밍과 다릅니다.</small>{opening&&<p className="notice">사진: <a href={scene.image.sourcePage} target="_blank" rel="noreferrer">{scene.image.creator} / {scene.image.source}</a> · 협업을 설명하는 자료 사진입니다.</p>}</div></section>
 <aside className="inspector"><div className="tabs"><button className={tab==='layout'?'active':''} onClick={()=>setTab('layout')}>배치</button><button className={tab==='discuss'?'active':''} onClick={()=>setTab('discuss')}>지침 · API</button></div>
 {tab==='layout'?<><section className="panel"><h2>선택한 요소</h2><div className="layers">{[...groups,...nodeKeys].map(k=><button className={selected===k?'active':''} key={k} onClick={()=>{setSelected(k);setEditing(true);player.current?.pause()}}>{names[k]||k}</button>)}</div>{box&&<><h3>{node?node.id:names[selected]}</h3><div className="fields">{['x','y','width','height'].map(k=><label key={k}>{({x:'X 위치',y:'Y 위치',width:'너비',height:'높이'} as any)[k]}<input type="number" step="1" value={Math.round(node?node[k]:(box as any)[k])} onChange={e=>{if(e.target.value!=='')updateValues({[k]:+e.target.value})}}/></label>)}</div><p className="notice">{node?'도식 좌표 800 × 560 · X/Y는 중심점입니다.':'화면 좌표 1080 × 1920 · X/Y는 좌상단입니다. 크기는 비율을 유지합니다.'}</p>{node?.role==='sticker'&&<>{['paper','blue'].includes(node.stickerAsset)&&<label>스티커 메모<input aria-label="스티커 메모" maxLength={60} value={node.label} onChange={e=>{const next=clone(draft);next.candidate.scenes[index].diagramSpec.nodes.find((n:any)=>n.id===selected).label=e.target.value;commit(next)}}/></label>}<button onClick={()=>{const next=clone(draft),d=next.candidate.scenes[index].diagramSpec;d.nodes=d.nodes.filter((n:any)=>n.id!==selected);d.events=d.events.filter((e:any)=>e.target!==selected);if((next.candidate.scenes[index].effects||[]).some((e:any)=>e.target===selected)){setFlash('연출 효과가 연결된 스티커는 제거할 수 없습니다.');return;}commit(next);setSelected('diagram')}}>선택한 스티커 제거</button><label>부착 대상<select value={node.stickerAttachment?.target||''} onChange={e=>attachment('target',e.target.value)}><option value="">독립 배치</option>{spec.nodes.filter((n:any)=>n.role!=='sticker'&&['rect','circle','blob'].includes(n.shape)).map((n:any)=><option key={n.id}>{n.id}</option>)}</select></label><label>겹침 프리셋<select value={node.stickerAttachment?.preset||''} onChange={e=>attachment('preset',e.target.value)}><option value="">선택 없음</option>{Object.entries(STICKER_ATTACHMENTS).filter(([,v])=>v.assets.includes(node.stickerAsset)).map(([k,v])=><option key={k} value={k}>{k} · {v.min*100}–{v.max*100}%</option>)}</select></label></>}</>}{common&&<p className="notice">공통 마무리 페이지는 이 검수에서 편집하지 않습니다.</p>}</section>
 <section className="panel"><h2>배치 검사</h2><div className={'status '+(diagnostics.length?'warn':'')}>{diagnostics.length?diagnostics.join('\n'):'도식의 중간 상태와 페이지 영역 검사 통과'}</div><p className="notice">편집 중에는 규칙을 벗어난 배치도 표시합니다. 최종 반영 전에는 실제 렌더 검수가 필요합니다.</p></section>
 {spec&&<section className="panel"><h2>스티커 추가</h2><div className="catalog">{['paper','blue','tape','check','star','underline'].map(k=><button key={k} className="asset" onClick={()=>addSticker(k)} title={(STICKER_USAGE as any)[k]}><img src={staticFile(`notebook/stickers/${k}.webp`)}/>{k} ＋</button>)}</div><p className="notice">추가 후 위치를 조절해 주세요. 메모 스티커는 가장자리, 체크는 실제로 선택한 항목에 붙입니다.</p></section>}</>:<><section className="panel"><h2>함께 정할 디자인 지침</h2><textarea aria-label="디자인 지침" rows={7} value={draft.guidelines} onChange={e=>setDraft({...draft,guidelines:e.target.value})}/><h3>현재 장면 메모</h3><textarea aria-label="장면 메모" rows={5} placeholder="예: 사진을 조금 더 크게, 체크는 v1 모서리로…" value={draft.notes[index]||''} onChange={e=>setDraft({...draft,notes:{...draft.notes,[index]:e.target.value}})}/><p className="notice">검수 JSON을 대화에 첨부하면 같은 배치와 메모를 이어서 논의할 수 있습니다. 실시간 공동 편집은 아직 지원하지 않습니다.</p></section><section className="panel"><h2>스티커 겹침 규칙</h2>{Object.entries(STICKER_ATTACHMENTS).map(([k,v])=><p className="notice" key={k}><b>{k} · {v.min*100}–{v.max*100}%</b><br/>{v.usage}</p>)}<p className="notice">비율의 분모는 스티커 면적입니다. 다른 객체는 합집합 기준 기본 20%, 설정 상한 40%. 글자 보호 영역은 가리지 않습니다.</p></section><section className="panel"><h2>API 초안</h2><p className="notice">도식 수정은 기존 candidate의 diagramSpec에 대응합니다. 페이지 배치는 검수 전용 layouts 제안값입니다. 제작 API 반영은 합의 후 진행합니다.</p><pre>{JSON.stringify({sceneIndex:index,coordinateSystem:node?'diagram-center-800x560':'page-top-left-1080x1920',selected,geometry:node||getLayout(selected),note:draft.notes[index]||''},null,2)}</pre><details><summary>검수 JSON 구조</summary><pre>{`{\n version: 1,\n sourceFingerprint: "원본 식별값",\n candidate: { scenes: [...] },\n layouts: { "장면:요소": { dx, dy, scale } },\n notes: { "장면": "논의 메모" },\n guidelines: "디자인 지침"\n}`}</pre></details></section></>}
 <button onClick={()=>{commit(fresh());setFlash('초기 배치로 돌아왔습니다. 실행 취소로 복원할 수 있습니다.')}}>전체 초기 배치로</button></aside></main>{flash&&<div role="status" className="flash">{flash}</div>}</>;
}
createRoot(document.getElementById('root')!).render(<App/>);
